#!/bin/sh
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, rename this file to "post-commit".

echo 
echo "*** Pushing changes to Origin"
echo

git push
